# Done and Done
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.2

# Mod Properties
mod_version=1.0.0
maven_group=com.resourcecraft
archives_base_name=resourcecraft

# Dependencies
fabric_version=0.146.1+26.1.2
midnightlib_version=1.9.2+26.1-fabric
modmenu_version=18.0.0-alpha.8
